### ISSUE TITLE
Using create -T appkit doesn't install run bower install

### ISSUE THREAD

**Issue by RyanHirsch** [taras/embersmith#3]
When creating a new application via `embersmith create -T appkit <DIR_NAME>` subsequently running `grunt server` serves up a page with errors.  The errors are resolved with a manual run of `bower install`. Documentation should be updated and ideally `embersmith create` would ensure the dependencies are there.

**Comment by taras** [comment]
I noticed this before, but I didn't want to hardcode the **create** command to do this. I was waiting for `bower install` to be added via **postinstall** hook in **package.json**. This was [done recently](https://github.com/stefanpenner/ember-app-kit/blob/master/package.json), so I can add this feature now.

I'm finishing up an article for Ember Sherpa and then I'll get back to Embersmith.

**Comment by RyanHirsch** [comment]
Awesome thank you so much for the work you've done so far on this
